### PR TITLE
Added demo link in README

### PR DESCRIPTION
**Pull request by lmammino**
🙃

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Haha, great idea! Thanks @lmammino 😄 

FYI @svrooij / #45 - this should work in the meantime!

**Comment by lmammino** [comment]
I love emojis and i could not love this amazing project! I thought it would be cool to be able to showcase what the library does with a quick runnable example

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @lmammino for docs

**Comment by lmammino** [comment]
Oh wow, thanks ❤️

**Pull request merged**
